### PR TITLE
update things to say winterlight and use winterlight urls

### PR DESCRIPTION
**Pull request by ian659**
Update the things to use this repo's urls, say winterlight, etc.

Also updated Dockerfile to use alpine3.9 because because the older version's wget wasn't playing nice with 2020's https.

### CODE REVIEW

**Comment by SashaSirotkin** [comment]
@ian659 Do we need to add this to our build pipeline?

**Comment by ian659** [comment]
> @ian659 Do we need to add this to our build pipeline?

I was wondering the same thing. I think the considerations should be,

1. will we ever need to change it? probably not, or at least not often. So automated builds might just cost more time to setup than they ever save.
2. is a build from the pipeline superior to a build a random member of the team has done locally? Yes, most definitely. It's repeatable and we can better account for what is actually in the image.

In our case I think the accountability out weights any time savings. Plus I think it would be a good chance for me to get some experience on our CI. However before I doing the automated build I would like to have a testing method for my manual build so I can confirm that at least what I have done to this point works. Fair?

**Comment by SashaSirotkin** [comment]
@ian659 
Fair! Let me know if you need my assistance in this matter.

Setting up automated builds is documented here: https://github.com/winterlightlabs/product-devops/blob/master/infrastructure/codebuild.md

I do want to move defining CodeBuild projects to Terraform in the future, but that's not immediately important.

**Comment by ian659** [comment]
@SashaSirotkin do we instructions for testing a rancher specific container? or possibly simulating a rancher environment?  Starting the container in docker causes it to complain about what seem to be rancher specific env vars and then terminate with a failure.

**Comment by ian659** [comment]
OK so I got the container running locally in rancher. It reaches the point of getting rejected by the letsencrypt API (expect because I am not using valid creds).

I am going try getting the automated build setup since I am now relatively what the container is try to do is sane.

**Review by SashaSirotkin — APPROVED** [review]

**Pull request merged**
